name: DEPLOY_BE_LAPAK_SANTRI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variable
      - uses: actions/checkout@v2
        env:
          PORT: ${{secrets.PORT}}
      - name: Print environment variable
        run: echo $PORT

